### ISSUE TITLE
Potentially interested in collaborating

### ISSUE THREAD

**Issue by obra** [maxgerhardt/gd32-arduino-core#1]
Hiya Max! 

We're looking at using a GD32F303 as the heart of an upcoming arduino-programmable keyboard running https://github.com/keyboardio/Kaleidoscope 

As we've been scouring the internet for a GD32 Arduino core, it looks like nobody's made a serious go of it up to now. We've been assuming that we're going to need to hack together our own core, but if you're game, it might make more sense to collaborate.

**Comment by maxgerhardt** [comment]
Hi, sounds interesting! We've set up a discord channel for discussion / communication of the contributors (but we've *just* started out so not a lot has happened), the link will be in the README.

That being said and reading through https://www.eevblog.com/forum/microcontrollers/psa-gd32f303-is-not-a-drop-in-substitute-for-stm32f303/

>I designed a board with a GD32F303 and discovered code for STM32F303 will not run on it (all peripheral accesses don't work), but code targeting STM32F103 does work and all tested peripherals (usb, dma, adc) work correctly. [..] So the GD32F303 really is just a F103 with more ram and flash

Maybe you can try the standard Arduino core (https://github.com/stm32duino/Arduino_Core_STM32) and set it up for a standard BluePill (STM32F103C8) and see if that works, for fun.

**Comment by algernon** [comment]
> Maybe you can try the standard Arduino core (https://github.com/stm32duino/Arduino_Core_STM32) and set it up for a standard BluePill (STM32F103C8) and see if that works, for fun.

We have worked with the stm32duino Core, and while it does appear to function, there's a licensing issue: namely that it uses the ST-provided HAL, which is [_not_ permitted to run on non-ST chips](https://www.st.com/SLA0044). As such, we can't use it with a GD MCU.

**Comment by maxgerhardt** [comment]
I've updated the `README` with more infos on licensing and collaboration through discord, thus closing :)
